# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Generate Unique time for docker image
      run: export IMAGE_ID=$(date +%s)
    
    - name: Build and Tag Docker image
      run: docker build . -t "docker.pkg.github.com/$GITHUB_REPOSITORY/spring-app:$IMAGE_ID" 
      env:
        IMAGE_ID : ${{env.IMAGE_ID}}    
            
    - name: Authenticate to Package
      run: docker login -u sreeprasadn -p $GITHUB_TOKEN docker.pkg.github.com 
      env:
        GITHUB_TOKEN: ${{secrets.PKG_TOKEN}} 
    
#    - name: Delete Previous Build Image 
#      run: docker image rm  "docker.pkg.github.com/$GITHUB_REPOSITORY/firmware-builder:latest"

    - name: Push image
      run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/spring-app:$IMAGE_ID"
      env:
        IMAGE_ID : ${{env.IMAGE_ID}} 

  
    
